export default {
  pages: [
    'pages/login/index',
    'pages/index/index',
    'pages/myBrowse/index',
    'pages/myLiked/index',
    'pages/usualMessage/index',
    'pages/traveler/index',
    'pages/myOrder/index',
    'pages/feedBack/index',
    'pages/setSex/index',
    'pages/setPassword/index',
    'pages/setAutograph/index',
    'pages/setName/index',
    'pages/setUp/index',
    'pages/myData/index',
    'pages/aboutUs/index',
    'pages/myToken/index',
    'pages/demo/index',
    'pages/webview/index',
    ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
}
